### ISSUE TITLE
cloudwatch-winston keeps trying to create the log group when it already exists

### ISSUE THREAD

**Issue by danberindei** [mifi/cloudwatch-winston#3]
`shouldCreateLogGroup: true` works great when the log group doesn't exist when the app starts, but if the log group already exists, `createdLogGroup` is never set to `true`, so `createLogGroup()` keeps running and failing with an error like this:

```
ResourceAlreadyExistsException: The specified log group already exists
    at de_ResourceAlreadyExistsExceptionRes (/home/dan/test-project/node_modules/@aws-sdk/client-cloudwatch-logs/dist-cjs/index.js:2286:21)
    at de_CommandError (/home/dan/test-project/node_modules/@aws-sdk/client-cloudwatch-logs/dist-cjs/index.js:2177:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/dan/test-project/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /home/dan/test-project/node_modules/@smithy/core/dist-cjs/index.js:165:18
    at async /home/dan/test-project/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /home/dan/test-project/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22
    at async createLogGroup (/home/dan/test-project/node_modules/cloudwatch-winston/index.js:58:7)
    at async Timeout.processQueue [as _onTimeout] (/home/dan/test-project/node_modules/cloudwatch-winston/index.js:114:55) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '43f6f16b',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  __type: 'ResourceAlreadyExistsException'
}
```

Since `createLogGroup()` already handles the `ResourceAlreadyExistsException`, the fix should be as simple as adding this [after the `// OK` line](https://github.com/mifi/cloudwatch-winston/blob/master/index.js#L66)

```
createdLogGroup = true
```

**Comment by mifi** [comment]
oops, thanks

**Comment by danberindei** [comment]
Thanks @mifi !
